import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage()
await page.setViewportSize({ width: 1440, height: 900 })
await page.goto('http://localhost:3000', { waitUntil: 'networkidle', timeout: 30000 })
await page.addStyleTag({ content: '.reveal { opacity: 1 !important; transform: none !important; transition: none !important; }' })
await page.waitForTimeout(500)
await page.screenshot({ path: 'C:/tmp/home-full.png', fullPage: true })
await page.setViewportSize({ width: 390, height: 844 })
await page.goto('http://localhost:3000', { waitUntil: 'networkidle', timeout: 30000 })
await page.addStyleTag({ content: '.reveal { opacity: 1 !important; transform: none !important; transition: none !important; }' })
await page.waitForTimeout(500)
await page.screenshot({ path: 'C:/tmp/home-mobile-full.png', fullPage: true })
await browser.close()
console.log('done')
